### ISSUE TITLE
UI bug on successful '/upload'

### ISSUE THREAD

**Issue by gabru-md** [fossasia/badgeyay#63]
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/badgeyay

**Current behavior:**

![by1](https://user-images.githubusercontent.com/25414121/30446396-f078819e-9980-11e7-9299-26ab1f4f35e7.png)

Footer overlaps the form whenever '/upload' is successful.
**Expected behavior:**

The footer must not overlap with the form.
It should stay either fixed on bottom or should be placed below the form everytime.

**Steps to reproduce:**

Changing some CSS would definitely do.
:D

**Comment by Pk13055** [comment]
I will work on this!

**Comment by niccokunzmann** [comment]
@Pk13055 Welcome! If you have any questions, please let us know.

**Comment by Pk13055** [comment]
Sure! I will have a pull within the day!

**Comment by gabru-md** [comment]
@Pk13055 any updates ?

**Comment by S2606** [comment]
@Pk13055 This bug is not only during the upload process but when the site starts.So please take it into consideration.

**Comment by jajodiaraghav** [comment]
This is a priority design bug.

**Comment by jajodiaraghav** [comment]
@Pk13055 Are you working on this or can I work on it?

**Comment by Pk13055** [comment]
I am working on this. Was caught up with query server, will be submitting a
PR by tomorrow

**Comment by jishnujayakumar** [comment]
@Pk13055 Are you done with #88 or should I start fixing the bug because I am free right now.

**Comment by Pk13055** [comment]
You can go ahead.

**Comment by niccokunzmann** [comment]
@jishnujayakumar If you are faster, you can do it. Best would be to work together with @Pk13055. Noone has the right to block progress. @Pk13055 can share the progress in a pull-request with [WIP] = work in progress.

**Comment by Pk13055** [comment]
Fixed (hopefully) as of #109
![screenshot from 2017-09-18 14-51-46](https://user-images.githubusercontent.com/13479308/30535887-7089b512-9c81-11e7-9d97-6a837d7a06f8.png)

**Comment by nanspro** [comment]
![workspace 1_014](https://user-images.githubusercontent.com/24641089/30537792-cdab9b46-9c88-11e7-95df-50fd6b78f4a3.png)
still not fixed

**Comment by jajodiaraghav** [comment]
Let me investigate!

**Comment by Pk13055** [comment]
@nanspro You might not be on the latest push? It seems fine on my computer.
![screenshot from 2017-09-18 15-52-25](https://user-images.githubusercontent.com/13479308/30537977-88b481b4-9c89-11e7-8203-bd420e404d14.png)

**Comment by jajodiaraghav** [comment]
@nanspro Cannot reproduce the issue.
Please rebase to latest!

**Comment by jajodiaraghav** [comment]
The issue has been fixed!
@nanspro Never forget to pull from upstream before testing :)

**Comment by nanspro** [comment]
![workspace 1_015](https://user-images.githubusercontent.com/24641089/30538254-c371d26a-9c8a-11e7-8c8f-17b3347812b6.png)
![workspace 1_016](https://user-images.githubusercontent.com/24641089/30538256-c5dae65e-9c8a-11e7-99c0-3863211c1a8d.png)
![workspace 1_017](https://user-images.githubusercontent.com/24641089/30538260-c99cd022-9c8a-11e7-803c-537cb6c4e36d.png)

Can you tell me what am i doing wrong @jajodiaraghav .

**Comment by jajodiaraghav** [comment]
Did you rebase you local?
1. `git checkout development`
2. `git pull upstream development --rebase`

**Comment by nanspro** [comment]
![workspace 1_018](https://user-images.githubusercontent.com/24641089/30539349-99547ee2-9c8f-11e7-869b-290221104e98.png)
already up to date
